version: '2'

services:

  primary.orderer:
    container_name: primary.orderer
    image: hyperledger/fabric-orderer
    dns_search: .
    volumes:
      - ./build/nodes/orderer:/etc/hyperledger/fabric

  peer1.org1:
    container_name: peer1.org1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1
      - CORE_PEER_ADDRESS=peer1.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1:7051
    volumes:
        - ./build/nodes/peer1.org1:/etc/hyperledger/fabric
    depends_on:
      - primary.orderer

  peer2.org1:
    container_name: peer2.org1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1
      - CORE_PEER_ADDRESS=peer2.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1:7051
    volumes:
        - ./build/nodes/peer2.org1:/etc/hyperledger/fabric
    depends_on:
      - primary.orderer
      - peer1.org1

  peer3.org1:
    container_name: peer3.org1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org1
      - CORE_PEER_ADDRESS=peer3.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1:7051
    volumes:
        - ./build/nodes/peer3.org1:/etc/hyperledger/fabric
    depends_on:
      - primary.orderer
      - peer1.org1

  peer4.org1:
    container_name: peer4.org1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.org1
      - CORE_PEER_ADDRESS=peer4.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1:7051
    volumes:
        - ./build/nodes/peer4.org1:/etc/hyperledger/fabric
    depends_on:
      - primary.orderer
      - peer1.org1

  cli:
    image: hyperledger/fabric-peer
    dns_search: .
    environment:
      - CORE_NEXT=true
      - CORE_LOGGING_LEVEL=DEBUG
    volumes:
      - ./build/nodes/cli:/etc/hyperledger/fabric
      - .:/cli
    working_dir: /cli
    depends_on:
      - primary.orderer
      - peer1.org1